[package]
name = "rust-todo"
version = "0.0.1"
edition = "2021"
license = "MIT"
keywords = [
    "guide",
    "todo",
]

[dependencies]
chrono = "0.4.26"
clap = { version = "4.5.4", features = ["derive"] }